use mercury_core::{
    ActorKind, PrototypeBackendCommand, PrototypeBackendCommandKind, PrototypeBackendCommandReason,
};

#[test]
fn backend_command_accepts_plaintext_free_human_session_request() {
    let command = PrototypeBackendCommand::new(
        32,
        ActorKind::Human,
        PrototypeBackendCommandKind::RunSessionHappyPath,
        0,
    );
    let decision = command.evaluate();
    let view = command.view();

    assert!(decision.accepted);
    assert_eq!(decision.reason, PrototypeBackendCommandReason::Accepted);
    assert!(decision.can_run_session);
    assert!(!decision.can_request_ai_draft);
    assert!(decision.emits_event_stream);
    assert_eq!(view.actor_kind_code, 1);
    assert_eq!(view.actor_kind_label, "human");
    assert_eq!(view.command_kind_code, 1);
    assert_eq!(view.command_kind_label, "run_session_happy_path");
    assert_eq!(view.reason_code, 0);
    assert_eq!(view.reason_label, "accepted");
    assert!(!view.can_request_ai_draft);
}

#[test]
fn backend_command_accepts_local_ai_draft_assist() {
    let command = PrototypeBackendCommand::new(
        32,
        ActorKind::LocalAi,
        PrototypeBackendCommandKind::RunLocalAiDraftAssist,
        0,
    );
    let decision = command.evaluate();
    let view = command.view();

    assert!(decision.accepted);
    assert_eq!(decision.reason, PrototypeBackendCommandReason::Accepted);
    assert!(!decision.can_run_session);
    assert!(decision.can_request_ai_draft);
    assert!(!decision.emits_event_stream);
    assert_eq!(view.actor_kind_code, 2);
    assert_eq!(view.actor_kind_label, "local_ai");
    assert_eq!(view.command_kind_code, 5);
    assert_eq!(view.command_kind_label, "run_local_ai_draft_assist");
    assert!(view.can_request_ai_draft);
}

#[test]
fn backend_command_accepts_human_production_store_session_request() {
    let command = PrototypeBackendCommand::new(
        32,
        ActorKind::Human,
        PrototypeBackendCommandKind::RunProductionStoreSessionWalReplayRequired,
        0,
    );
    let decision = command.evaluate();
    let view = command.view();

    assert!(decision.accepted);
    assert_eq!(decision.reason, PrototypeBackendCommandReason::Accepted);
    assert!(decision.can_run_session);
    assert!(!decision.can_request_ai_draft);
    assert!(decision.emits_event_stream);
    assert_eq!(view.command_kind_code, 8);
    assert_eq!(
        view.command_kind_label,
        "run_production_store_session_wal_replay_required"
    );
    assert_eq!(view.reason_label, "accepted");
}

#[test]
fn backend_command_accepts_human_platform_adapter_request() {
    let command = PrototypeBackendCommand::new(
        32,
        ActorKind::Human,
        PrototypeBackendCommandKind::RunPlatformLocalStoreAdapterDesktopReady,
        0,
    );
    let decision = command.evaluate();
    let view = command.view();

    assert!(decision.accepted);
    assert_eq!(decision.reason, PrototypeBackendCommandReason::Accepted);
    assert!(decision.can_run_session);
    assert!(!decision.can_request_ai_draft);
    assert!(decision.emits_event_stream);
    assert_eq!(view.command_kind_code, 10);
    assert_eq!(
        view.command_kind_label,
        "run_platform_local_store_adapter_desktop_ready"
    );
}

#[test]
fn backend_command_rejects_local_ai_session_requests() {
    let decision = PrototypeBackendCommand::new(
        32,
        ActorKind::LocalAi,
        PrototypeBackendCommandKind::RunSessionHappyPath,
        0,
    )
    .evaluate();

    assert!(!decision.accepted);
    assert_eq!(
        decision.reason,
        PrototypeBackendCommandReason::ActorNotAllowed
    );
    assert_eq!(decision.actor_kind, ActorKind::LocalAi);
    assert!(!decision.can_run_session);
    assert!(!decision.can_request_ai_draft);
    assert!(!decision.emits_event_stream);
}

#[test]
fn backend_command_rejects_bad_id_length_before_session() {
    let decision = PrototypeBackendCommand::new(
        12,
        ActorKind::Human,
        PrototypeBackendCommandKind::RunSessionHappyPath,
        0,
    )
    .evaluate();

    assert!(!decision.accepted);
    assert_eq!(
        decision.reason,
        PrototypeBackendCommandReason::BadCommandIdLength
    );
    assert!(!decision.can_run_session);
    assert!(!decision.can_request_ai_draft);
    assert!(!decision.emits_event_stream);
}

#[test]
fn backend_command_rejects_plaintext_payloads() {
    let decision = PrototypeBackendCommand::new(
        32,
        ActorKind::Human,
        PrototypeBackendCommandKind::RunSessionHappyPath,
        1,
    )
    .evaluate();

    assert!(!decision.accepted);
    assert_eq!(
        decision.reason,
        PrototypeBackendCommandReason::PlaintextPayloadForbidden
    );
}

#[test]
fn backend_command_rejects_remote_ai_actor() {
    let decision = PrototypeBackendCommand::new(
        32,
        ActorKind::RemoteAi,
        PrototypeBackendCommandKind::RunSessionAiRejected,
        0,
    )
    .evaluate();

    assert!(!decision.accepted);
    assert_eq!(
        decision.reason,
        PrototypeBackendCommandReason::ActorNotAllowed
    );
    assert_eq!(decision.actor_kind, ActorKind::RemoteAi);
}

#[test]
fn backend_command_kinds_have_stable_codes_and_labels() {
    let cases = [
        (
            PrototypeBackendCommandKind::RunSessionHappyPath,
            1,
            "run_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunSessionBootstrapBlocked,
            2,
            "run_session_bootstrap_blocked",
        ),
        (
            PrototypeBackendCommandKind::RunSessionRelayRejected,
            3,
            "run_session_relay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSessionAiRejected,
            4,
            "run_session_ai_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalAiDraftAssist,
            5,
            "run_local_ai_draft_assist",
        ),
        (
            PrototypeBackendCommandKind::RunProductionStoreSessionHappyPath,
            6,
            "run_production_store_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunProductionStoreSessionKeychainRejected,
            7,
            "run_production_store_session_keychain_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunProductionStoreSessionWalReplayRequired,
            8,
            "run_production_store_session_wal_replay_required",
        ),
        (
            PrototypeBackendCommandKind::RunProductionStoreSessionWriteRejected,
            9,
            "run_production_store_session_write_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunPlatformLocalStoreAdapterDesktopReady,
            10,
            "run_platform_local_store_adapter_desktop_ready",
        ),
        (
            PrototypeBackendCommandKind::RunPlatformLocalStoreAdapterMobileHardwareRequired,
            11,
            "run_platform_local_store_adapter_mobile_hardware_required",
        ),
        (
            PrototypeBackendCommandKind::RunPlatformLocalStoreAdapterPlaintextForbidden,
            12,
            "run_platform_local_store_adapter_plaintext_forbidden",
        ),
        (
            PrototypeBackendCommandKind::RunPlatformLocalStoreAdapterAppLockRequired,
            13,
            "run_platform_local_store_adapter_app_lock_required",
        ),
        (
            PrototypeBackendCommandKind::RunReceiveSessionHappyPath,
            14,
            "run_receive_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunReceiveSessionAckRejected,
            15,
            "run_receive_session_ack_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunReceiveSessionOrderingGap,
            16,
            "run_receive_session_ordering_gap",
        ),
        (
            PrototypeBackendCommandKind::RunReceiveSessionStoreWriteRejected,
            17,
            "run_receive_session_store_write_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncDeliveryReady,
            18,
            "run_inbound_sync_delivery_ready",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncIdle,
            19,
            "run_inbound_sync_idle",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncBootstrapBlocked,
            20,
            "run_inbound_sync_bootstrap_blocked",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncTransportOffline,
            21,
            "run_inbound_sync_transport_offline",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncPlaintextPreviewForbidden,
            22,
            "run_inbound_sync_plaintext_preview_forbidden",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncSessionHappyPath,
            23,
            "run_inbound_sync_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncSessionIdle,
            24,
            "run_inbound_sync_session_idle",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncSessionSyncRejected,
            25,
            "run_inbound_sync_session_sync_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunInboundSyncSessionReceiveRejected,
            26,
            "run_inbound_sync_session_receive_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAuthenticatedRelaySourceDeliveryReady,
            27,
            "run_authenticated_relay_source_delivery_ready",
        ),
        (
            PrototypeBackendCommandKind::RunAuthenticatedRelaySourceIdle,
            28,
            "run_authenticated_relay_source_idle",
        ),
        (
            PrototypeBackendCommandKind::RunAuthenticatedRelaySourceAuthRejected,
            29,
            "run_authenticated_relay_source_auth_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAuthenticatedRelaySourcePlaintextForbidden,
            30,
            "run_authenticated_relay_source_plaintext_forbidden",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectStoreUploadReady,
            31,
            "run_media_object_store_upload_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectStorePlaintextRejected,
            32,
            "run_media_object_store_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectStoreAutoDownloadRejected,
            33,
            "run_media_object_store_auto_download_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectStoreOversizeRejected,
            34,
            "run_media_object_store_oversize_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaUploadSessionHappyPath,
            35,
            "run_media_upload_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunMediaUploadSessionPlaintextRejected,
            36,
            "run_media_upload_session_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaUploadSessionSealRejected,
            37,
            "run_media_upload_session_seal_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaUploadSessionStoreWriteRejected,
            38,
            "run_media_upload_session_store_write_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceAdapterReady,
            39,
            "run_media_service_adapter_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceAdapterAuthMissing,
            40,
            "run_media_service_adapter_auth_missing",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceAdapterPlaintextForbidden,
            41,
            "run_media_service_adapter_plaintext_forbidden",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceAdapterDigestUnverified,
            42,
            "run_media_service_adapter_digest_unverified",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceUploadSessionHappyPath,
            43,
            "run_media_service_upload_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceUploadSessionMediaRejected,
            44,
            "run_media_service_upload_session_media_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceUploadSessionAuthRejected,
            45,
            "run_media_service_upload_session_auth_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceUploadSessionDigestUnverified,
            46,
            "run_media_service_upload_session_digest_unverified",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceDownloadReady,
            47,
            "run_media_service_download_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceDownloadPlaintextPreviewRejected,
            48,
            "run_media_service_download_plaintext_preview_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceDownloadAuthMissing,
            49,
            "run_media_service_download_auth_missing",
        ),
        (
            PrototypeBackendCommandKind::RunMediaServiceDownloadDigestUnverified,
            50,
            "run_media_service_download_digest_unverified",
        ),
        (
            PrototypeBackendCommandKind::RunMediaDownloadSessionHappyPath,
            51,
            "run_media_download_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunMediaDownloadSessionDownloadRejected,
            52,
            "run_media_download_session_download_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaDownloadSessionStoreWriteRejected,
            53,
            "run_media_download_session_store_write_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaDownloadSessionOpenRejected,
            54,
            "run_media_download_session_open_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaRetentionDeleteAndEvictReady,
            55,
            "run_media_retention_delete_and_evict_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaRetentionRetainReady,
            56,
            "run_media_retention_retain_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaRetentionHoldRejected,
            57,
            "run_media_retention_hold_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaRetentionAuthMissing,
            58,
            "run_media_retention_auth_missing",
        ),
        (
            PrototypeBackendCommandKind::RunMediaCleanupSessionHappyPath,
            59,
            "run_media_cleanup_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunMediaCleanupSessionRetainReady,
            60,
            "run_media_cleanup_session_retain_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaCleanupSessionRetentionRejected,
            61,
            "run_media_cleanup_session_retention_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaCleanupSessionCacheAbsent,
            62,
            "run_media_cleanup_session_cache_absent",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexRemoteAndLocalReady,
            63,
            "run_media_object_index_remote_and_local_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexAbsentUploadReady,
            64,
            "run_media_object_index_absent_upload_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexDeletePendingReady,
            65,
            "run_media_object_index_delete_pending_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexDeletedTerminal,
            66,
            "run_media_object_index_deleted_terminal",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexPlaintextMetadataRejected,
            67,
            "run_media_object_index_plaintext_metadata_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexBadLifecycleRejected,
            68,
            "run_media_object_index_bad_lifecycle_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexStoreWriteReady,
            69,
            "run_media_object_index_store_write_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexStoreIndexRejected,
            70,
            "run_media_object_index_store_index_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexStoreBadObjectRejected,
            71,
            "run_media_object_index_store_bad_object_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMediaObjectIndexStoreDeletedSnapshot,
            72,
            "run_media_object_index_store_deleted_snapshot",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaUploadSessionHappyPath,
            73,
            "run_indexed_media_upload_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaUploadSessionServiceRejected,
            74,
            "run_indexed_media_upload_session_service_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaUploadSessionIndexStoreRejected,
            75,
            "run_indexed_media_upload_session_index_store_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaDownloadSessionHappyPath,
            76,
            "run_indexed_media_download_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaDownloadSessionManifestRejected,
            77,
            "run_indexed_media_download_session_manifest_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaDownloadSessionNotDownloadable,
            78,
            "run_indexed_media_download_session_not_downloadable",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaDownloadSessionDownloadRejected,
            79,
            "run_indexed_media_download_session_download_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaCleanupSessionHappyPath,
            80,
            "run_indexed_media_cleanup_session_happy_path",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaCleanupSessionManifestRejected,
            81,
            "run_indexed_media_cleanup_session_manifest_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaCleanupSessionNotCleanable,
            82,
            "run_indexed_media_cleanup_session_not_cleanable",
        ),
        (
            PrototypeBackendCommandKind::RunIndexedMediaCleanupSessionCleanupRejected,
            83,
            "run_indexed_media_cleanup_session_cleanup_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousCredentialIssuerTrustReady,
            84,
            "run_anonymous_credential_issuer_trust_ready",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousCredentialIssuerTrustTransparencyRequired,
            85,
            "run_anonymous_credential_issuer_trust_transparency_required",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousCredentialIssuerTrustRevoked,
            86,
            "run_anonymous_credential_issuer_trust_revoked",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousCredentialIssuerTrustPartitioningMetadataRejected,
            87,
            "run_anonymous_credential_issuer_trust_partitioning_metadata_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousGroupMembershipProofReady,
            88,
            "run_anonymous_group_membership_proof_ready",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousGroupMembershipProofHighSecurityPqRequired,
            89,
            "run_anonymous_group_membership_proof_high_security_pq_required",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousGroupMembershipProofReplayRejected,
            90,
            "run_anonymous_group_membership_proof_replay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousGroupMembershipProofRouteBindingRequired,
            91,
            "run_anonymous_group_membership_proof_route_binding_required",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousGroupMembershipProofPlaintextIdentityRejected,
            92,
            "run_anonymous_group_membership_proof_plaintext_identity_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousRateLimitNullifierReady,
            93,
            "run_anonymous_rate_limit_nullifier_ready",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousRateLimitNullifierReplayRejected,
            94,
            "run_anonymous_rate_limit_nullifier_replay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousRateLimitNullifierLimitExceeded,
            95,
            "run_anonymous_rate_limit_nullifier_limit_exceeded",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousRateLimitNullifierOpaqueStoreRequired,
            96,
            "run_anonymous_rate_limit_nullifier_opaque_store_required",
        ),
        (
            PrototypeBackendCommandKind::RunGroupRelayEnvelopeReady,
            97,
            "run_group_relay_envelope_ready",
        ),
        (
            PrototypeBackendCommandKind::RunGroupRelayEnvelopeTranscriptSyncRequired,
            98,
            "run_group_relay_envelope_transcript_sync_required",
        ),
        (
            PrototypeBackendCommandKind::RunGroupRelayEnvelopeTranscriptRekeyRequired,
            99,
            "run_group_relay_envelope_transcript_rekey_required",
        ),
        (
            PrototypeBackendCommandKind::RunGroupRelayEnvelopeMissingDeliveryToken,
            100,
            "run_group_relay_envelope_missing_delivery_token",
        ),
        (
            PrototypeBackendCommandKind::RunGroupRelayEnvelopePlaintextMetadataRejected,
            101,
            "run_group_relay_envelope_plaintext_metadata_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousNullifierStoreReady,
            102,
            "run_anonymous_nullifier_store_ready",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousNullifierStoreReplayRejected,
            103,
            "run_anonymous_nullifier_store_replay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousNullifierStorePlaintextMetadataRejected,
            104,
            "run_anonymous_nullifier_store_plaintext_metadata_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunAnonymousCredentialIssuerTrustWitnessAuditRejected,
            105,
            "run_anonymous_credential_issuer_trust_witness_audit_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunGroupChatMlsReady,
            106,
            "run_group_chat_mls_ready",
        ),
        (
            PrototypeBackendCommandKind::RunGroupChatMlsSetupRequired,
            107,
            "run_group_chat_mls_setup_required",
        ),
        (
            PrototypeBackendCommandKind::RunGroupChatMembershipSyncRequired,
            108,
            "run_group_chat_membership_sync_required",
        ),
        (
            PrototypeBackendCommandKind::RunGroupChatPlaintextMetadataForbidden,
            109,
            "run_group_chat_plaintext_metadata_forbidden",
        ),
        (
            PrototypeBackendCommandKind::RunGroupChatHighSecurityMlsRequired,
            110,
            "run_group_chat_high_security_mls_required",
        ),
        (
            PrototypeBackendCommandKind::RunGroupChatHighSecurityPqRequired,
            111,
            "run_group_chat_high_security_pq_required",
        ),
        (
            PrototypeBackendCommandKind::RunGroupChatMlsProviderSecurityRequired,
            112,
            "run_group_chat_mls_provider_security_required",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceStoreReady,
            113,
            "run_mls_provider_evidence_store_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceStoreGateRejected,
            114,
            "run_mls_provider_evidence_store_gate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceStoreDuplicateRejected,
            115,
            "run_mls_provider_evidence_store_duplicate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceStorePlaintextRejected,
            116,
            "run_mls_provider_evidence_store_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceUseReady,
            117,
            "run_mls_provider_evidence_use_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceUseMissing,
            118,
            "run_mls_provider_evidence_use_missing",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceUseExpired,
            119,
            "run_mls_provider_evidence_use_expired",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceUseSuiteMismatch,
            120,
            "run_mls_provider_evidence_use_suite_mismatch",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderEvidenceUsePlaintextRejected,
            121,
            "run_mls_provider_evidence_use_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageAdmissionReady,
            122,
            "run_mls_key_package_admission_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageAdmissionGroupRejected,
            123,
            "run_mls_key_package_admission_group_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageAdmissionLifetimeRejected,
            124,
            "run_mls_key_package_admission_lifetime_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageAdmissionSuiteMismatch,
            125,
            "run_mls_key_package_admission_suite_mismatch",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageAdmissionCredentialRejected,
            126,
            "run_mls_key_package_admission_credential_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageAdmissionReplayRejected,
            127,
            "run_mls_key_package_admission_replay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageAdmissionPlaintextRejected,
            128,
            "run_mls_key_package_admission_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageConsumeStoreReady,
            154,
            "run_mls_key_package_consume_store_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageConsumeStoreAdmissionRejected,
            155,
            "run_mls_key_package_consume_store_admission_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageConsumeStoreDuplicateRejected,
            156,
            "run_mls_key_package_consume_store_duplicate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageConsumeStoreBadShape,
            157,
            "run_mls_key_package_consume_store_bad_shape",
        ),
        (
            PrototypeBackendCommandKind::RunMlsKeyPackageConsumeStorePlaintextRejected,
            158,
            "run_mls_key_package_consume_store_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeSendOutboxReady,
            159,
            "run_mls_welcome_send_outbox_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeSendOutboxConsumeRejected,
            160,
            "run_mls_welcome_send_outbox_consume_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeSendOutboxDuplicateTransactionRejected,
            161,
            "run_mls_welcome_send_outbox_duplicate_transaction_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeSendOutboxKeyPackageQueued,
            162,
            "run_mls_welcome_send_outbox_key_package_queued",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeSendOutboxBadShape,
            163,
            "run_mls_welcome_send_outbox_bad_shape",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeSendOutboxPlaintextRejected,
            164,
            "run_mls_welcome_send_outbox_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsMembershipTransactionReady,
            165,
            "run_mls_membership_transaction_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsMembershipTransactionBindingRejected,
            166,
            "run_mls_membership_transaction_binding_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsMembershipTransactionStorageRejected,
            167,
            "run_mls_membership_transaction_storage_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsMembershipTransactionDuplicateRejected,
            168,
            "run_mls_membership_transaction_duplicate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsMembershipTransactionPlaintextRejected,
            169,
            "run_mls_membership_transaction_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseSecurityReady,
            170,
            "run_local_store_database_security_ready",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseSecurityPlaintextRejected,
            171,
            "run_local_store_database_security_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseSecurityWalRejected,
            172,
            "run_local_store_database_security_wal_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseSecurityBackupRejected,
            173,
            "run_local_store_database_security_backup_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseSecuritySecretLifecycleRejected,
            174,
            "run_local_store_database_security_secret_lifecycle_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseAdapterSelectionReady,
            175,
            "run_local_store_database_adapter_selection_ready",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseAdapterSelectionLicenseRejected,
            176,
            "run_local_store_database_adapter_selection_license_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseAdapterSelectionFipsRejected,
            177,
            "run_local_store_database_adapter_selection_fips_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseAdapterSelectionMigrationRejected,
            178,
            "run_local_store_database_adapter_selection_migration_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunLocalStoreDatabaseAdapterSelectionSupplyChainRejected,
            179,
            "run_local_store_database_adapter_selection_supply_chain_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderAdapterSelectionReady,
            180,
            "run_mls_provider_adapter_selection_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderAdapterSelectionProviderRejected,
            181,
            "run_mls_provider_adapter_selection_provider_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderAdapterSelectionPqDraftRejected,
            182,
            "run_mls_provider_adapter_selection_pq_draft_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderAdapterSelectionStorageRejected,
            183,
            "run_mls_provider_adapter_selection_storage_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsProviderAdapterSelectionSupplyChainRejected,
            184,
            "run_mls_provider_adapter_selection_supply_chain_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSecureBackupRestoreReady,
            185,
            "run_secure_backup_restore_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSecureBackupRestoreRecoveryRejected,
            186,
            "run_secure_backup_restore_recovery_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSecureBackupRestorePlaintextRejected,
            187,
            "run_secure_backup_restore_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSecureBackupRestoreMlsRekeyRejected,
            188,
            "run_secure_backup_restore_mls_rekey_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSecureBackupRestoreCloudPolicyRejected,
            189,
            "run_secure_backup_restore_cloud_policy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventChainReady,
            190,
            "run_sealed_audit_event_chain_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventChainPlaintextRejected,
            191,
            "run_sealed_audit_event_chain_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventChainRollbackRejected,
            192,
            "run_sealed_audit_event_chain_rollback_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventChainWitnessRejected,
            193,
            "run_sealed_audit_event_chain_witness_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventChainBindingRejected,
            194,
            "run_sealed_audit_event_chain_binding_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventStoreReady,
            195,
            "run_sealed_audit_event_store_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventStoreChainRejected,
            196,
            "run_sealed_audit_event_store_chain_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventStoreDuplicateRejected,
            197,
            "run_sealed_audit_event_store_duplicate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventStoreRollbackRejected,
            198,
            "run_sealed_audit_event_store_rollback_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditEventStorePlaintextRejected,
            199,
            "run_sealed_audit_event_store_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessCheckpointReady,
            200,
            "run_sealed_audit_witness_checkpoint_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessCheckpointStoreRejected,
            201,
            "run_sealed_audit_witness_checkpoint_store_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessCheckpointQuorumRejected,
            202,
            "run_sealed_audit_witness_checkpoint_quorum_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessCheckpointSplitViewRejected,
            203,
            "run_sealed_audit_witness_checkpoint_split_view_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessCheckpointPrivacyRejected,
            204,
            "run_sealed_audit_witness_checkpoint_privacy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessClientReady,
            205,
            "run_sealed_audit_witness_client_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessClientConflict,
            206,
            "run_sealed_audit_witness_client_conflict",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessClientUnavailable,
            207,
            "run_sealed_audit_witness_client_unavailable",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessClientPolicyRejected,
            208,
            "run_sealed_audit_witness_client_policy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditWitnessClientMonitorPrivacyRejected,
            209,
            "run_sealed_audit_witness_client_monitor_privacy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofBundleReady,
            210,
            "run_sealed_audit_proof_bundle_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofBundleClientRejected,
            211,
            "run_sealed_audit_proof_bundle_client_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofBundleStaleWitness,
            212,
            "run_sealed_audit_proof_bundle_stale_witness",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofBundlePolicyRejected,
            213,
            "run_sealed_audit_proof_bundle_policy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofBundlePrivacyRejected,
            214,
            "run_sealed_audit_proof_bundle_privacy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofCacheReady,
            215,
            "run_sealed_audit_proof_cache_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofCacheBundleRejected,
            216,
            "run_sealed_audit_proof_cache_bundle_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofCacheDuplicateRejected,
            217,
            "run_sealed_audit_proof_cache_duplicate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofCachePolicyStale,
            218,
            "run_sealed_audit_proof_cache_policy_stale",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditProofCachePlaintextRejected,
            219,
            "run_sealed_audit_proof_cache_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditVerifierPolicyReady,
            220,
            "run_sealed_audit_verifier_policy_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditVerifierPolicyExpired,
            221,
            "run_sealed_audit_verifier_policy_expired",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditVerifierPolicyKeyRotationRequired,
            222,
            "run_sealed_audit_verifier_policy_key_rotation_required",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditVerifierPolicyMonitorPrivacyRejected,
            223,
            "run_sealed_audit_verifier_policy_monitor_privacy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditVerifierPolicyPlaintextRejected,
            224,
            "run_sealed_audit_verifier_policy_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditIncidentEvidenceReady,
            225,
            "run_sealed_audit_incident_evidence_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditIncidentEvidencePolicyRejected,
            226,
            "run_sealed_audit_incident_evidence_policy_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditIncidentEvidenceMissingProofReport,
            227,
            "run_sealed_audit_incident_evidence_missing_proof_report",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditIncidentEvidenceSplitView,
            228,
            "run_sealed_audit_incident_evidence_split_view",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditIncidentEvidencePlaintextRejected,
            229,
            "run_sealed_audit_incident_evidence_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditRecoveryExportReady,
            230,
            "run_sealed_audit_recovery_export_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditRecoveryExportIncidentRejected,
            231,
            "run_sealed_audit_recovery_export_incident_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditRecoveryExportQuorumRequired,
            232,
            "run_sealed_audit_recovery_export_quorum_required",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditRecoveryExportRollbackRejected,
            233,
            "run_sealed_audit_recovery_export_rollback_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditRecoveryExportPlaintextRejected,
            234,
            "run_sealed_audit_recovery_export_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditDatabaseAdapterReady,
            235,
            "run_sealed_audit_database_adapter_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditDatabaseAdapterEncryptionRejected,
            236,
            "run_sealed_audit_database_adapter_encryption_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditDatabaseAdapterAppendOnlyRejected,
            237,
            "run_sealed_audit_database_adapter_append_only_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportTransportReady,
            238,
            "run_sealed_audit_private_report_transport_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportTransportPlaintextRejected,
            239,
            "run_sealed_audit_private_report_transport_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportOutboxReady,
            240,
            "run_sealed_audit_private_report_outbox_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportOutboxTransportRejected,
            241,
            "run_sealed_audit_private_report_outbox_transport_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportOutboxReplayRejected,
            242,
            "run_sealed_audit_private_report_outbox_replay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportOutboxRateLimitRejected,
            243,
            "run_sealed_audit_private_report_outbox_rate_limit_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportOutboxPlaintextRejected,
            244,
            "run_sealed_audit_private_report_outbox_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReceiptReady,
            245,
            "run_sealed_audit_private_report_receipt_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReceiptOutboxRejected,
            246,
            "run_sealed_audit_private_report_receipt_outbox_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReceiptMissing,
            247,
            "run_sealed_audit_private_report_receipt_missing",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReceiptTransparencyRejected,
            248,
            "run_sealed_audit_private_report_receipt_transparency_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReceiptPlaintextRejected,
            249,
            "run_sealed_audit_private_report_receipt_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReconciliationReady,
            250,
            "run_sealed_audit_private_report_reconciliation_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReconciliationReceiptRejected,
            251,
            "run_sealed_audit_private_report_reconciliation_receipt_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReconciliationRetryRejected,
            252,
            "run_sealed_audit_private_report_reconciliation_retry_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReconciliationFalseDeliveryRejected,
            253,
            "run_sealed_audit_private_report_reconciliation_false_delivery_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportReconciliationPlaintextRejected,
            254,
            "run_sealed_audit_private_report_reconciliation_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportGatewayEvidenceReady,
            255,
            "run_sealed_audit_private_report_gateway_evidence_ready",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportGatewayEvidenceReconciliationRejected,
            256,
            "run_sealed_audit_private_report_gateway_evidence_reconciliation_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportGatewayEvidenceUnavailableRejected,
            257,
            "run_sealed_audit_private_report_gateway_evidence_unavailable_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportGatewayEvidenceAccountabilityRejected,
            258,
            "run_sealed_audit_private_report_gateway_evidence_accountability_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunSealedAuditPrivateReportGatewayEvidencePlaintextRejected,
            259,
            "run_sealed_audit_private_report_gateway_evidence_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeAdmissionReady,
            129,
            "run_mls_welcome_admission_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeAdmissionSecretsMissing,
            130,
            "run_mls_welcome_admission_secrets_missing",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeAdmissionTreeRejected,
            131,
            "run_mls_welcome_admission_tree_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeAdmissionConfirmationRejected,
            132,
            "run_mls_welcome_admission_confirmation_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeAdmissionTieBreakRejected,
            133,
            "run_mls_welcome_admission_tie_break_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeAdmissionReplayRejected,
            134,
            "run_mls_welcome_admission_replay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeAdmissionPlaintextRejected,
            135,
            "run_mls_welcome_admission_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitAdmissionReady,
            136,
            "run_mls_commit_admission_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitAdmissionBadEpoch,
            137,
            "run_mls_commit_admission_bad_epoch",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitAdmissionAuthRejected,
            138,
            "run_mls_commit_admission_auth_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitAdmissionPathRejected,
            139,
            "run_mls_commit_admission_path_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitAdmissionTieBreakRejected,
            140,
            "run_mls_commit_admission_tie_break_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitAdmissionReplayRejected,
            141,
            "run_mls_commit_admission_replay_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitAdmissionPlaintextRejected,
            142,
            "run_mls_commit_admission_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitReplayStoreReady,
            143,
            "run_mls_commit_replay_store_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitReplayStoreAdmissionRejected,
            144,
            "run_mls_commit_replay_store_admission_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitReplayStoreDuplicateRejected,
            145,
            "run_mls_commit_replay_store_duplicate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitReplayStoreLocalMemberRemoved,
            146,
            "run_mls_commit_replay_store_local_member_removed",
        ),
        (
            PrototypeBackendCommandKind::RunMlsCommitReplayStorePlaintextRejected,
            147,
            "run_mls_commit_replay_store_plaintext_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeReplayStoreReady,
            148,
            "run_mls_welcome_replay_store_ready",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeReplayStoreAdmissionRejected,
            149,
            "run_mls_welcome_replay_store_admission_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeReplayStoreDuplicateRejected,
            150,
            "run_mls_welcome_replay_store_duplicate_rejected",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeReplayStoreKeyPackageReused,
            151,
            "run_mls_welcome_replay_store_key_package_reused",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeReplayStoreBadShape,
            152,
            "run_mls_welcome_replay_store_bad_shape",
        ),
        (
            PrototypeBackendCommandKind::RunMlsWelcomeReplayStorePlaintextRejected,
            153,
            "run_mls_welcome_replay_store_plaintext_rejected",
        ),
    ];

    for (kind, code, label) in cases {
        assert_eq!(kind.code(), code);
        assert_eq!(kind.label(), label);
    }
}
