// Generated by tools/gen_policy_attestations.py --write. Do not edit by hand.

export const HELIX_POLICY_BOUNDARY = "Helix owns deterministic policy, validators, state-machine checks, and proof artifacts. Rust and reviewed libraries own production cryptography, ratchets, key storage, and platform bindings." as const;

export const POLICY_ATTESTATIONS = {
  "account_recovery": {
    "componentPolicies": [],
    "displayName": "Account recovery",
    "name": "account_recovery",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/account_recovery_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "account recovery gate",
    "rustMirrorTests": [
      "core/rust/mercury-core/tests/account_recovery_vectors.rs",
      "core/rust/mercury-core/tests/decider_exhaustive_diff.rs"
    ],
    "sourceHash": "91bc5e26b3e41b5660583eb1fe224c751b0bb177577c6373d951206786f0527d",
    "sourceHashShort": "91bc5e26b3e4",
    "testHashShort": "0f5f2e16f261",
    "vectorFileCount": 24,
    "vectorHashShort": "e3fc0d3486ae"
  },
  "ai_grant": {
    "componentPolicies": [],
    "displayName": "AI grant",
    "name": "ai_grant",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/ai_grant_policy_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "AI principal scope gate",
    "rustMirrorTests": [
      "core/rust/mercury-policy/tests/ai_grant_vectors.rs"
    ],
    "sourceHash": "4ce57f56d4f3564ab9af8b1fcf938ddbe5e9c9b45fe558f126f1f71d810e966d",
    "sourceHashShort": "4ce57f56d4f3",
    "testHashShort": "892994ce3851",
    "vectorFileCount": 20,
    "vectorHashShort": "45c630a02b58"
  },
  "ai_grant_lifecycle": {
    "componentPolicies": [],
    "displayName": "AI grant lifecycle",
    "name": "ai_grant_lifecycle",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/ai_grant_lifecycle_policy_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "AI grant expiry and revoke gate",
    "rustMirrorTests": [
      "core/rust/mercury-policy/tests/ai_grant_lifecycle_vectors.rs"
    ],
    "sourceHash": "c10cd3afbe3f66f0f7a871ecce4e66f93cbece51ca605e6b86555397508a05c9",
    "sourceHashShort": "c10cd3afbe3f",
    "testHashShort": "a21fd3dcc420",
    "vectorFileCount": 15,
    "vectorHashShort": "76b9577897ba"
  },
  "bootstrap_decide": {
    "componentPolicies": [],
    "displayName": "Client bootstrap",
    "name": "bootstrap_decide",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/bootstrap_decide_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "client bootstrap and startup gate",
    "rustMirrorTests": [
      "core/rust/mercury-core/tests/bootstrap_decide_vectors.rs",
      "core/rust/mercury-core/tests/decider_exhaustive_diff.rs"
    ],
    "sourceHash": "1706b3b1722cb79f25ab63a5d44866c0d76c514c165af6df4d2dde2a52a50db2",
    "sourceHashShort": "1706b3b1722c",
    "testHashShort": "1c67b9956ca2",
    "vectorFileCount": 29,
    "vectorHashShort": "21cb3948e2ed"
  },
  "envelope": {
    "componentPolicies": [],
    "displayName": "Envelope",
    "name": "envelope",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/envelope_policy_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "message envelope and downgrade gate",
    "rustMirrorTests": [
      "core/rust/mercury-policy/tests/envelope_vectors.rs"
    ],
    "sourceHash": "e3e6a00847f0f7befdd92e47b7e03b529d542bdd59fb60a206ac0d30033f9881",
    "sourceHashShort": "e3e6a00847f0",
    "testHashShort": "259db8d01d4c",
    "vectorFileCount": 12,
    "vectorHashShort": "f0cd317b57bd"
  },
  "inbound_sync": {
    "componentPolicies": [],
    "displayName": "Inbound sync",
    "name": "inbound_sync",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/inbound_sync_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "client inbound sync gate",
    "rustMirrorTests": [
      "core/rust/mercury-core/tests/inbound_sync_vectors.rs",
      "core/rust/mercury-core/tests/decider_exhaustive_diff.rs"
    ],
    "sourceHash": "6eddc0d8bee4ef321ea91e265fb6ef2b3b948f6ceba39729e382ca47768e8d6e",
    "sourceHashShort": "6eddc0d8bee4",
    "testHashShort": "040062ce1f26",
    "vectorFileCount": 15,
    "vectorHashShort": "bd615ee42ea6"
  },
  "outbound_decide": {
    "componentPolicies": [],
    "displayName": "Outbound send",
    "name": "outbound_decide",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/outbound_decide_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "client outbound send gate",
    "rustMirrorTests": [
      "core/rust/mercury-core/tests/outbound_decide_vectors.rs",
      "core/rust/mercury-core/tests/decider_exhaustive_diff.rs"
    ],
    "sourceHash": "493974aee97980ba7a2ea3ee774577037c32bc506a91d261620dd022ed0fb499",
    "sourceHashShort": "493974aee979",
    "testHashShort": "d43b599726c3",
    "vectorFileCount": 16,
    "vectorHashShort": "fcd1a18d1a66"
  },
  "platform_decision": {
    "componentPolicies": [],
    "displayName": "Platform decision",
    "name": "platform_decision",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/platform_decision_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "capability view projection",
    "rustMirrorTests": [
      "core/rust/mercury-core/tests/platform_decision_vectors.rs"
    ],
    "sourceHash": "290c81e3eb1be02aa0fcc417632672800cf5c1fe39f338c8a8b1d882fb9f910d",
    "sourceHashShort": "290c81e3eb1b",
    "testHashShort": "12d6a2aa094c",
    "vectorFileCount": 44,
    "vectorHashShort": "b636ccc9f911"
  },
  "policy_pipeline": {
    "componentPolicies": [
      "envelope",
      "room_epoch",
      "ai_grant",
      "ai_grant_lifecycle"
    ],
    "displayName": "Policy pipeline",
    "name": "policy_pipeline",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/policy_pipeline_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "component policy composition",
    "rustMirrorTests": [
      "core/rust/mercury-policy/tests/policy_pipeline_vectors.rs",
      "core/rust/mercury-core/tests/core_policy_vectors.rs"
    ],
    "sourceHash": "8eff76505cde8dbb4eec66b3581ce7cab33b3d8eef7820e902080c312ffbc778",
    "sourceHashShort": "8eff76505cde",
    "testHashShort": "03fc5730db27",
    "vectorFileCount": 15,
    "vectorHashShort": "4bbfaaaa401b"
  },
  "receive_decide": {
    "componentPolicies": [],
    "displayName": "Client receive",
    "name": "receive_decide",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/receive_decide_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "client receive gate",
    "rustMirrorTests": [
      "core/rust/mercury-core/tests/receive_decide_vectors.rs",
      "core/rust/mercury-core/tests/decider_exhaustive_diff.rs"
    ],
    "sourceHash": "1f01478a8c867124b6425e323f6a515c250c5568bb7ddfabf4829ef8fc46dcbd",
    "sourceHashShort": "1f01478a8c86",
    "testHashShort": "8d46167c103f",
    "vectorFileCount": 19,
    "vectorHashShort": "71db12fed0a7"
  },
  "relay_submit": {
    "componentPolicies": [],
    "displayName": "Relay submit",
    "name": "relay_submit",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/relay_submit_policy_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "opaque relay submission gate",
    "rustMirrorTests": [
      "core/rust/mercury-policy/tests/relay_submit_vectors.rs",
      "core/rust/mercury-core/tests/relay_submission.rs"
    ],
    "sourceHash": "d7aca5db1f425afa0c13d39695987278ba03589b103112b3f5fae3d9feba73a0",
    "sourceHashShort": "d7aca5db1f42",
    "testHashShort": "a566f641a4f2",
    "vectorFileCount": 15,
    "vectorHashShort": "d48bdac76a23"
  },
  "room_epoch": {
    "componentPolicies": [],
    "displayName": "Room epoch",
    "name": "room_epoch",
    "optionalGates": [
      "from_raw_k1_elf_exit_42"
    ],
    "policyJson": "policy/room_epoch_policy_v1.json",
    "productionRuntime": "rust_mirror",
    "requiredGates": [
      "python_vector_check",
      "rust_vector_or_exhaustive_test",
      "helix_hash",
      "helix_proof_obligations",
      "helix_elf_exit_42"
    ],
    "role": "room epoch and membership state gate",
    "rustMirrorTests": [
      "core/rust/mercury-policy/tests/room_epoch_vectors.rs"
    ],
    "sourceHash": "4a9eb8922b07c97c6c233bc83e748ea1a76b234206c1964d2c3b71db4cbaee33",
    "sourceHashShort": "4a9eb8922b07",
    "testHashShort": "1f83667cb894",
    "vectorFileCount": 19,
    "vectorHashShort": "b7cbe97b9129"
  }
} as const;

export const DECISION_SOURCE_POLICY = {
  "client_bootstrap": "bootstrap_decide",
  "client_policy": "policy_pipeline",
  "client_receive": "receive_decide",
  "outbound_send": "outbound_decide",
  "policy_pipeline": "policy_pipeline"
} as const;

export type PolicyName = keyof typeof POLICY_ATTESTATIONS;

export function policyForDecisionSource(source: string): PolicyName | undefined {
  return DECISION_SOURCE_POLICY[source as keyof typeof DECISION_SOURCE_POLICY];
}

export function attestationForDecisionSource(source: string) {
  const policy = policyForDecisionSource(source);
  return policy ? POLICY_ATTESTATIONS[policy] : undefined;
}

export function componentAttestations(policy: PolicyName) {
  return POLICY_ATTESTATIONS[policy].componentPolicies.map(
    (name) => POLICY_ATTESTATIONS[name as PolicyName],
  );
}
